### ISSUE TITLE
Things you have to fix

### ISSUE THREAD

**Issue by itsjtwright** [ConstructCommunity/awesome-construct#4]
Each link must end with a period
Don't mention Construct 2 in descriptions.
Bitballoon needs a description

**Comment by Armaldio** [comment]
@itsjtwright If I replace "Construct 2" by "the editor" for example, is it right ?

Edit: Is the list better now ?

**Comment by itsjtwright** [comment]
Possibly "the engine"? I think of construct 2 as an engine

**Comment by itsjtwright** [comment]
I would try sending a pr to awesome now, seeing what the lead guy says.

**Comment by Armaldio** [comment]
ok thanks :)
